language: generic
sudo : required
services:
  - docker

before_install:
  - docker build -t xalster/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xalster/docker-react npm run test

after_success:
  - docker build -t xalster/multi-client ./client
  - docker build -t xalster/multi-nginx ./nginx
  - docker build -t xalster/multi-server ./server
  - docker build -t xalster/multi-worker ./worker